### ISSUE TITLE
Add skeleton to the identities page and the identity page.

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#130]
## What we want

The idea here is to have something more smooth when you connect. 

Cause you have nothing and then suddenly all your identities appear. 

here is a small video of the problem.

Voilà le problème sur la page identities (`identities.ts`).

https://user-images.githubusercontent.com/78437165/218699427-1761af65-7d86-4012-ba20-fab2da2d251c.mp4

Voilà le problème sur la page d'identité (`tokenId.ts`).

https://user-images.githubusercontent.com/78437165/218700581-a4f1f60c-9184-481c-9353-54202d11b1b2.mp4

## Context

We use material UI ==> here is the tool to do it https://mui.com/material-ui/react-skeleton/ 

It's an easy PR for someone that wants to begin with this repo. 

If you make a PR, make a video of how it looks on the PR description !

**Comment by phklive** [comment]
i take it let's go
