### ISSUE TITLE
starknet rs fix issue 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#135]

**Comment by fricoben** [comment]
Finish https://github.com/xJonathanLEI/starknet-rs/pull/266

**Comment by Th0rgal** [comment]
I made a pull request to bring .stark names support natively to starknet rs. It works but doesn't pass the linter check and the developer asked for a few refactors.

**Comment by Th0rgal** [comment]
we just need a merge now

**Comment by fricoben** [comment]
Jonathan does not want to merge the PR
