### ISSUE TITLE
Create a starknet id js sdk

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#136]
# **Describe the solution you'd like**
A typescript sdk built on top of starknetjs allowing to resolve domains and easily manipulate StarknetID data for a website

# **Specs**
You need to be able to create a StarknetIDNavigator (or whatever you want to call it) which takes as input the network (testnet, mainnet) and optionally the contract to query (should be deduced from testnet and mainnet). This object would give multiple methods:

## Encoding (should be accessible outside of the Navigator object)
``encode(word : string) -> felt : BN``
``decode(felt : BN) -> word : string``
/!\ domain should end in .stark
``encode_domain(domain : string) -> encoded_domain : BN[]`` 
``decode_domain(encoded_domain : BN[]) -> domain : string``

## Resolving domains
``domain_to_address(domain : string) -> address : BN``
``address_to_domain(address : BN) -> domain : string``
``domain_to_starknetid(domain : string) -> starknetid : uint128`` // I'm not sure it fits in a number, if it is not the case, let's keep a BN

## Resolving data
> See https://github.com/starknet-id/contract#starknetid-contract

``starknetid_to_data(starknetid, field) -> BN``
``starknetid_to_extended_data(starknetid, field, length) -> BN[]``
``starknetid_to_unbounded_data(starknetid, field) -> BN[]``

``starknetid_to_verifier_data(starknetid, field, verifier) -> BN``
``starknetid_to_extended_verifier_data(starknetid, field, length, verifier) -> BN[]``
``starknetid_to_unbounded_verifier_data(starknetid, field, verifier) -> BN[]``

It would be nice to add the same methods but taking a domain as input, it would automatically resolve it to a starknet_id e.g.:
``domain_to_data(domain, field) -> BN``

You can use https://github.com/starknet-id/sbt.starknet.id/blob/main/src/hooks/naming.ts and https://docs.starknet.id/for-devs/encoding-algorithm for reference.

**Comment by irisdv** [comment]
Interested to work on this issue !

**Comment by fricoben** [comment]
Done with class by @irisdv
