### ISSUE TITLE
Front End refactor

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#139]
**Is your feature request related to a problem? Please describe.**

Right now the token ID page on `app.starknet.id/identities/[tokenId]` is not really user friendly and does not show our will to make a starknet identity as a starknet passport. More than that our fonts do not represent this fun aspect that we want to give to the website and the brand.

**Describe the solution you'd like**

1° Change the title font
2° Change the Leaves everywhere we used the old ones
3° Integrate the new Model for the tokenId page 

It's an issue to give to someone that is experimented with HTML/CSS and web integration. It's very difficult but I would say it can take some time because of the small details like responsiveness...

**Additional context**

[Here is the Figma](https://www.figma.com/file/4mulnURcKlouTh00F0o5w1/Starknet?node-id=1%3A2) where you can find the maquette and the UI kit. 

[Here are the new leaves](https://github.com/starknet-id/app.starknet.id/files/10811226/Leaves.zip) that should replace the old ones everywhere.

[Here is the new title font](https://github.com/starknet-id/app.starknet.id/files/10811235/quick_zap.zip) that should be in the title class now.

**Comment by phklive** [comment]
I'll take it.
