### ISSUE TITLE
Automatic Renewal front-end

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#178]
This feature should allow the user to subscribe to an automatic renewal for his domain. It should highlight the fact that it prevents people from losing their domain and it saves them the gas fees.

**Comment by fricoben** [comment]
Here for the front end you need to add a button that will say "Enable automatic renewal" on the `[tokenId.tsx]` page

<img width="305" alt="Capture d’écran 2023-04-11 à 20 34 02" src="https://user-images.githubusercontent.com/78437165/231257266-b94b33b2-d411-4c04-859f-6d384403ca7e.png">

Here we want to add this kind of button saying "Enable auto-renewal". 

When you click on it a modal opens, it will explain how the auto-renewal works (you can use `modalMessage.tsx`) and have a button that will launch the tx for auto-renewal. 

if someone enabled the auto-renewal you have the button that says "Disable auto renewal", the same `modalMessage.tsx` but the button will disable the auto-renewal.
