### ISSUE TITLE
Move to starknet js only

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#341]
We have trouble with starknet react.

Could be cool to move everything to starknet js directly at some point.

**Comment by Cevedale** [comment]
Transitioning from JavaScript to StarkNet involves a comprehensive process encompassing the adaptation of smart contracts to the Cairo programming language, the installation of essential StarkNet development tools, the adjustment of dependencies to align with StarkNet requirements, rigorous testing on the StarkNet testnet, deployment of the modified smart contracts on the StarkNet mainnet or testnet, updating the frontend to ensure seamless interaction with StarkNet, conducting thorough security audits to fortify the smart contracts against vulnerabilities, informing users about the migration to StarkNet, and maintaining vigilant oversight over the entire system to promptly address and rectify any emerging issues.
