### ISSUE TITLE
Profile Pic Feature 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#416]
Design https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID-design?node-id=1481%3A15157&mode=dev

Brief coming from @Th0rgal

**Comment by Th0rgal** [comment]
Here is the brief: https://app.skiff.com/drive/file/bc62662c-d7dd-42fe-9748-c50fd8b230db
