### ISSUE TITLE
Fix the Starky bot with the Starkscan API and apply this to our discord

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#458]
Starky bot is not working, make it work in production on our discord

**Comment by Marchand-Nicolas** [comment]
Starky is back to work on both goerli and mainnet networks.
The roles of a user are going to be refreshed when:
- he connects his wallets
- he makes a tx on the starknetId  (in our case) contract
- he uses the /starky-refresh command

So if a user made a tx before this update, this won't refresh his roles. I'll try to work on a new update which will add more indexers which will continuously reindex data up to last year or something like that (In addition to the indexers which process all new incoming tx) so the user would also get its roles refreshed multiple times if he did a tx in this period of time

**Comment by fricoben** [comment]
`he makes a tx on the starknetId (in our case) contract` I don't understand this can you explain a bit more

**Comment by Marchand-Nicolas** [comment]
> `he makes a tx on the starknetId (in our case) contract` I don't understand this can you explain a bit more

If the user makes a transfer, a mint, or a burn of a StarknetID NFT, this will refresh its Discord roles

**Comment by fricoben** [comment]
Nico fixed everything here
