### ISSUE TITLE
Precision on PFP setting 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#461]
## Description

We need to create a better screen when someone sets his PFP because right now you know that you dond't have whitelisted NFTs but you don't know how to get one, which collection are whitelisted ...

<img width="1293" alt="Capture d’écran 2023-10-21 à 10 28 43" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/569371ea-e753-4f5f-9c84-88316b8ca7f8">

## PROPOSED TODO

- [x] @Kevils make some propositions and we define a design
- [ ] @irisdv or @ayushtom use the constant file to directly integrate the design

**Comment by Kevils** [comment]
Loom : https://www.loom.com/share/df236c1a6639487a90cef9d99d4243fa

Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=1926%3A19449&mode=design&t=j9jw2Ye7KGBb9P31-1
