### ISSUE TITLE
Create Stark Tribe mint page

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#469]
Design Brief ==> https://app.skiff.com/file/cf9ab5a2-c353-4868-a949-8e29c3d01ad9

**Comment by Kevils** [comment]
Figma file available : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=2167%3A19544&mode=design&t=ZJEf0jVfrXhgwzG7-1
