### ISSUE TITLE
sns.id subdomain distribution

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#471]
updated technical brief: https://app.skiff.com/file/f264e6a8-d8ac-4a4e-8b2b-4cb38953b2ce

## Description
After several discussions with the Bonfida team building sns.id we decided to collaborate with them with a cross-chain subdomain distribution. 

- They will distribute .stark.sol subdomains on Solana.
- We'll distribute .sol.stark subdomains on Starknet.

This feature will need a dedicated front-end as we did with https://xplorer.starknet.id/  (closed but here is a video to show you what it looked like ==> https://www.loom.com/share/7d2e2bb52d0c46219b1076ccdaf40887)

We'll need to create a new page on the front-end of app.starknet.id where users will need to connect their Solana wallet (@Kevils you can go use some Solana apps with the [phantom wallet](https://chrome.google.com/webstore/detail/phantom/bfnaelmomeimhlpmgjnjophhpkkoljpa) to understand. If a Solana user has a sns.id domain, we'll be able to get one `.sol.stark domain`.

The things we'll change are: 
- Images and colors to fit Starknet ID tribe branding
- Add two connection buttons, 1 for Solana wallet (to verify the user has a .sol domain on Solana) and 1 Starknet to pass the transaction.

## Repositeries to reuse
// On the design and code part of the app, we need to reuse this repo code and design ==> https://github.com/starknet-id/og.starknet.id
The Starknet contract will be this contract ==> https://github.com/starknet-id/subdomain_distribution

### DESIGN
- [ ] @Kevils make the Figma of the front-end with a new image and two connection buttons for Solana wallet and Starknet wallet.

### Dev
- [ ] Update all the dependencies of the [og repo](https://github.com/starknet-id/og.starknet.id) (to make it up to date with Starknet React and starknet.js version)
- [ ] Make this old repo work with [the new Cairo 1 contract](https://github.com/starknet-id/subdomain_distribution) (just adapt transactions call if needed).
- [ ] Fork the repo and name it sns.starknet.id
- [ ] Implement Figma Design with Starknet and Solana wallet connection
- [ ] Add an endpoint on api.starknet.id which verifies a Solana wallet confirmation signature and output the associated signature to allow the user to mint its associated domain as a subdomain or sol.stark.
- [ ] Verify that the user owns a sns.id domain with an API (to be found, we'll need to ask the sns.id team)  
- [ ] Make a whitelisting process using next.js server to launch the Starknet `Claim name` transaction only if the user has a .sol domain on Solana (in [og.starknet.id](https://github.com/starknet-id/og.starknet.id) we also had a whitelisting process but the condition was different).

**Comment by Kevils** [comment]
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=2155%3A17420&mode=design&t=5ffC1KmDtPRq5OzL-1

**Comment by Kevils** [comment]
ETH subdomain distribution : https://github.com/starknet-id/app.starknet.id/issues/492

**Comment by fricoben** [comment]
@Th0rgal created several issues for this features, it makes more sense
