### ISSUE TITLE
Bug: it is not possible to transfer an expired domain

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#478]
**Describe the bug**
When transferring a starknetid nft linked to a domain, we automatically update domain_to_address to the receiver address, which is not possible on an expired domain.

**To Reproduce**
Try to transfer a NFT linked to an expired domain to another user from the app

**Screenshots**
<img width="629" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/7c9bb2f5-1fb1-499e-8492-e0633121c9c0">

**Comment by fricoben** [comment]
Set domain to address doesn't exist anymore
