### ISSUE TITLE
auto renewal doesn't support taxes

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#482]
<img width="1177" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/c6b46f3f-a073-46d9-8938-c58dd9e1acf8">

When toggling auto renewal on a domain paid with taxes (in this example California), the allowance is not big enough so we can't renew it. We could fix it by adding a way to retrieve the exact price after tax or by allowing the maximum. I suggest the former.

**Comment by fricoben** [comment]
done
