### ISSUE TITLE
on hold txs accepted on l1

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#491]
<img width="501" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/467d239e-7438-4be6-a9df-4df5f55917da">

<img width="1035" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/47b1beee-fb74-405a-a8c4-830e3ccd98fa">

https://testnet.starkscan.co/tx/0x17235c4000298e9f123191ed3d4468b3fa6944eefce61304a6302f84e7ba81e

**Comment by fricoben** [comment]
it's also buggy on starknet quest
