### ISSUE TITLE
Impossible to click on `View Less`

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#508]
<img width="651" alt="Capture d’écran 2023-11-22 à 16 04 00" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/7cba8aa2-6637-4e6b-b032-1a1a88332085">

Impossible to click on `View Less` because the feedback is before it. For this feedbacks and also the others we should add the possibility to close them like so.

<img width="761" alt="Capture d’écran 2023-11-28 à 17 43 58" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/cc700c3c-59ef-4dbf-86fd-458ecc234ca6">

Ressources
https://mui.com/material-ui/react-snackbar/
https://mui.com/material-ui/react-alert/

**Comment by Kevils** [comment]
For me, we should simply be able to close the feedback even if it reappears on refresh.
I don't think it's our feedback used in a normal way.

Use this component : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=1496%3A4488&mode=design&t=vhPGKStwJOUycGTo-1

**Comment by Kevils** [comment]
![image](https://github.com/starknet-id/app.starknet.id/assets/144677881/0e2684da-f066-4e66-9a40-8eb17027ceef)
