### ISSUE TITLE
Fix pipeline metahash to avoid double forms by users

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#538]
should work:
https://goerli.api.starknet.id/renewal/get_metahash?addr=0x1c7b4df74c309c5086c39aeab1aa6ac8eb3562ce3f7c644b6a363e24f6d1af

for this metahash: 0x927848e207629b381eda2f7d9c1817027226b2a6672deea2ecda2121c9aefa

**Comment by fricoben** [comment]
Actually it's because it goes the `sale` collection, I'll let @irisdv manage this issue for next sprint

**Comment by irisdv** [comment]
So apparently it's an issue with the indexer because this data should be indexed in the `sale` collection.

**Comment by irisdv** [comment]
So this can be explained by : 
- issue when indexing where the user did not have an entry in the `sales` collection. Tested locally and it should be solved by restarting the indexer 
- For this particular user, when buying a domain the `meta_hash` was empty. When he toggles auto renewal, we generate a `meta_hash` that is then stored in the `auto_renew_updates` collection which results in our endpoint still not returning any data. This is a edge case so closing the issue.
