### ISSUE TITLE
E2E: Use of domain in identityChangeModal doesn't work

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#581]
<img width="717" alt="Capture d’écran 2023-12-18 à 15 02 38" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/a197b1ad-b377-4cfd-9160-aa796bea36a9">

**Comment by Th0rgal** [comment]
Linked to: https://github.com/starknet-id/starknetid.js/issues/20

This will be fixed when starknetid.js is updated

**Comment by Th0rgal** [comment]
Fixed
