### ISSUE TITLE
E2E: You buy a domain on top of a subdomain

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#587]
https://testnet.starkscan.co/tx/0x5ea1c5275d617f8c2f7c6b9b585e8ee68d5c6f2d774b2ecf9275408bf50c5d8
550396886414 had the subdomain avimak.motty.fricoben.stark

**Comment by Th0rgal** [comment]
<img width="580" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/cb362801-4daa-42c0-850b-b5ed126c419b">
Cannot reproduce on a domain, I will retry on a subdomain

**Comment by Th0rgal** [comment]
Should be fixed after an update of the contract
