### ISSUE TITLE
E2E: Set as main domain in the right conditions contract check

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#590]
https://testnet.starkscan.co/tx/0x64e83da97829ec9454fa00bccd7d19de7443aa59b417cc0744565b7c66b686f

Prints an error on the contract when I call `addr_to_domain` (I don't see the domain on my wallet + button so we have a contract problem here)

**Comment by fricoben** [comment]
https://testnet.starkscan.co/tx/0x154d02dbe122dc06136b320d720f962f69d41f9ad65d400b07fa026997a18fb

This transaction has been made through the contract directly and it works well. 

We have to investigate the first TX then

**Comment by Th0rgal** [comment]
> https://testnet.starkscan.co/tx/0x154d02dbe122dc06136b320d720f962f69d41f9ad65d400b07fa026997a18fb

This way of doing it is deprecated, set_main_id should be called, but you are right there is a bug, I'm on it

**Comment by Th0rgal** [comment]
Fixed by changing the app so that it sets a reverse record if necessary.
