### ISSUE TITLE
PFP collections page

### ISSUE THREAD

**Issue by Kevils** [starknet-id/app.starknet.id#593]
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=2538%3A26866&mode=design&t=Z2rmcB5JsUalcTtB-1

Loom : https://www.loom.com/share/1db07535d3174829960414e7d9c63b04

**Comment by fricoben** [comment]
@Marchand-Nicolas for this sprint I want you so simply add Starknet Quest as one of Starknet ID collections and all the others that there is on the design as suggestions ! Thanks a lot !

So you need to code only the page that lists the collection atm (and add every relevant links)
