### ISSUE TITLE
New card animation by hovering

### ISSUE THREAD

**Issue by Kevils** [starknet-id/app.starknet.id#594]
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=2539%3A28700&mode=design&t=Z2rmcB5JsUalcTtB-1

Loom : https://www.loom.com/share/ac010f32b8064bb4968fdb47f9496488

**Comment by Damkols** [comment]
I would like to work on this issue.
I just forked and cloned the repository to my computer, I installed the project dependencies.
But when I run the project locally with npm run dev, I get this error
``Server Error
Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `undefined` instead.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
``
