### ISSUE TITLE
E2E: indexer encoding problem 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#596]
Indexer problem on subdomains encoding. 

I created the domain cairo1.lococon.stark here https://testnet.starkscan.co/tx/0x546ba02af35e26807e1ea6e80af4e6a8b6e8654b5f4b6e290136941d1c3ac1a

It shows me c.cairo1.lococon.stark

**Comment by fricoben** [comment]
Another example here https://goerli.app.starknet.id/identities/655504233681

Creation of the subdomain here https://testnet.starkscan.co/contract/0x003bab268e932d2cecd1946f100ae67ce3dff9fd234119ea2f6da57d16d29fce

**Comment by Th0rgal** [comment]
Fixed
