### ISSUE TITLE
E2E: `get_non_subscribed_domains` takes too much time

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#597]
https://goerli.api.starknet.id/renewal/get_non_subscribed_domains?addr=0x072D4F3FA4661228ed0c9872007fc7e12a581E000FAd7b8f3e3e5bF9E6133207

Takes too much time to charge, you can test here https://goerli.app.starknet.id/subscription

**Comment by Th0rgal** [comment]
fixed by https://github.com/starknet-id/api.starknet.id/pull/56
