### ISSUE TITLE
E2E: `generateSuggestedDomains` is not working

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#598]
We have an infinite loading on the suggested domains section, I checked and it's because we used `domain_to_expiry`. 

I propose you search on the code like this all the queries that you changed like so:
<img width="175" alt="Capture d’écran 2023-12-22 à 13 13 24" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/4fb6e594-1d8e-443e-9664-6b60a8a2bb0d">

Just to make sure we won't forget some in the future.

A problem that we wouldn't have if we do https://github.com/starknet-id/app.starknet.id/issues/603

**Comment by Th0rgal** [comment]
domain_to_expiry was added back
