### ISSUE TITLE
E2E: impossible to send money from Braavos anymore

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#599]
<img width="401" alt="Capture d’écran 2023-12-22 à 13 20 04" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/1e6be36d-1ca9-47b0-b8da-c9b561476769">
<img width="361" alt="Capture d’écran 2023-12-22 à 13 20 15" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/d356f9e5-3cf4-456b-a226-732dca9009e9">

linked to https://github.com/starknet-id/app.starknet.id/issues/581 it comes from the new interface of the function `domain_to_address` in my opinion we shouldn't change the interface because everyone will have to update and it'll take ages (braavos, argent ...). 

Is there a workaround ?

**Comment by Th0rgal** [comment]
Update: fixed in Argent, will contract Braavos
