### ISSUE TITLE
E2E: `domain_to_data` resolves to a different address than `domain_to_addr`

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#600]
After making this [tx](https://testnet.starkscan.co/tx/0x5afcfee8963b694bc330ef75c79bc307f61d7caf8c057a722d0729b6e172d59) (change address of a domain). 

`domain_to_data` now points to 0 when `domain_to_address` points to the right address
<img width="1207" alt="Capture d’écran 2023-12-22 à 13 39 45" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/79249f76-3070-4aa4-ae9f-f9b500a7c615">

Please check that you resolve the same way for all the read functions and the `domain_to_data` one

**Comment by Th0rgal** [comment]
The logic of domain_to_addr changed, now it resolves by order of priority to :
- what's written in domain_to_data
- what's written on your starknetid
- the starknetid's owner

**Comment by fricoben** [comment]
OK. 

So it appear that `domain_data` is only used for dev purposes and it's basically checking the data hardcoded
