### ISSUE TITLE
BUG: Production link is down

### ISSUE THREAD

**Issue by ramanand-rv** [starknet-id/app.starknet.id#608]
**Describe the bug**
Cannot access production link

**To Reproduce**

1. Go to [Production Link](https://www.app.starknet.id/
)

**Expected behavior**
Site should open

**Screenshots**
![image](https://github.com/starknet-id/app.starknet.id/assets/80584888/cd68d361-f143-445f-91b9-ed5265659754)

**Desktop (please complete the following information):**

- OS: [Window 10]
- Browser [Brave, Chrome]

**Comment by fricoben** [comment]
no it's not
