### ISSUE TITLE
Transaction manager issue

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#610]
User have bug on transaction manager on the front-end where he still sees the tx as pending when they are accepted for several weeks

ticket: https://discord.com/channels/1025416762835095674/1189660550175666207
tx: https://starkscan.co/tx/0x03a5ef40fcb60d2c4242d89ca1da4a684a37176ceae666dedf2ddb8301381e00

**Comment by irisdv** [comment]
Fixed
