### ISSUE TITLE
Verification generates an error even though it worked

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#618]
<img width="672" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/b41a678a-8853-46cb-add5-a3232da136c5">

**Comment by hymns12** [comment]
Hello, i need the proper description of the bug issues so that i could work on it ASAP . Thank you

**Comment by hymns12** [comment]
Hello Good day can i work on this project??
