### ISSUE TITLE
Category and empty string when no boost

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#636]
<img width="701" alt="Capture d’écran 2024-01-11 à 17 34 09" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/1e840292-44d6-4078-bd9e-a2337bd0d047">
<img width="1057" alt="Capture d’écran 2024-01-11 à 17 34 18" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/6398de3c-873e-4233-a373-a2e113da6803">

When I click nothing appears. So we can: 

- [ ] Add a text when No quest are being boosted atm

**Comment by Marchand-Nicolas** [comment]
Moved to starknet.quest's repo https://github.com/starknet-id/starknet.quest/issues/457
