### ISSUE TITLE
Add image too boosted categorie 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#637]
Boosted category has AVNU helmet as an image and it's a bit strange. 

I propose we add this image (in webp): https://cdn.discordapp.com/attachments/995431305066065950/1195059783636619367/fricoben_Isometric_view_of_a_dollar_sign_game_asset_digital_art_ed584976-3c46-40f6-8fa4-4d8f1147f2ee.png

Webp convertisseur https://onlineconvertfree.com/convert-format/png-to-webp/

**Comment by Marchand-Nicolas** [comment]
Moved to starknet.quest's repo: https://github.com/starknet-id/starknet.quest/issues/459
