### ISSUE TITLE
Social Medias Verification

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#642]
**Describe the bug**
After each verification about social medias, an error page appears, so you need to refresh the page. This is a mental obstacle to continuing with other verifications.

**Expected behavior**
Have an user experience without need to refresh the page after each social medias verification.

**Screenshots**

<img width="1512" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/57441909/325a4da0-eb2b-472c-b781-383b97027a24">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome

**Comment by fricoben** [comment]
closed
