### ISSUE TITLE
Wrong address into referral page

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#643]
**Describe the bug**
I had already used another address to interact with Starknet.id and open different pages (like referral) before purchasing a domain with a new address. After purchasing a domain, a window popped up concerning the referral program. However, when I opened the referral window, the page was linked to my previous address.

**Expected behavior**
Have the right address linked to the referral program page.

**Screenshots**
<img width="1512" alt="image2" src="https://github.com/starknet-id/app.starknet.id/assets/57441909/2a1c5fd3-a405-4cc6-8fb1-0c5c93ab7856">

**Comment by fricoben** [comment]
This is actually not a bug, just the fact you connected with this address before on the referral page
