### ISSUE TITLE
Improve UI after purchasing a domain

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#644]
## Description
Once we have bought a domain, we stay on the purchase page, thinking that eventually we'll have to buy it again and/or use a new domain name.

<img width="1512" alt="image3" src="https://github.com/starknet-id/app.starknet.id/assets/57441909/f3c220de-d1bc-400a-8232-5b732c958c01">

## PROPOSED TODO

Probably be redirected into another page.

**Comment by fricoben** [comment]
We can just redirect to `/identities` when the modal is closed :)
