### ISSUE TITLE
Domain ownership is not being verified

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#651]
**Details**
Domain is not being identified by starknet.id and starkent quest contracts
while user has an active domain minted 6 months back .
There is no trading of activity done on the Domain .

Domain name : gigihadid.stark
Domain validity is till : JULY 21 , 2024

**Domain in starknet.id:** https://app.starknet.id/search?domain=gigihadid.stark

**User wallet address** : 0x062dc5f812db53e56feaf45aa55445a40ffe3992b167d49ddf7b62d66df712e2  [ Argentx wallet ]

**Transaction hash for mint** : https://starkscan.co/tx/0x024d14dd4ccfe78408566341c09ce68723d1b6247a7bcaa80863e850a2761f3b

**Domain activity :** https://starkscan.co/nft/0x05dbdedc203e92749e2e746e2d40a768d966bd243df04a6b712e222bc040a9af/378867419040#activity

**Additional details :**
![image](https://github.com/starknet-id/app.starknet.id/assets/55296770/d96e1317-6895-4972-9f2e-287cb06d5928)
![image](https://github.com/starknet-id/app.starknet.id/assets/55296770/642cf1ec-a402-4bd7-9c69-bf7a54045fb8)

**User tickets regarding this issue :**

https://discord.com/channels/1025416762835095674/1194864264838656080
https://discord.com/channels/1025416762835095674/1194636250951458936
https://discord.com/channels/1025416762835095674/1189660550175666207
https://discord.com/channels/1025416762835095674/1188127485481721907
https://discord.com/channels/1154728104112177262/1198555741078966272
https://discord.com/channels/1154728104112177262/1195999831106273341
https://discord.com/channels/1154728104112177262/1195899253172740116
https://discord.com/channels/1154728104112177262/1185806633801109575

**Comment by revengexd** [comment]
Updated info : Link to discord ticket added these are the users who have this issue

**Comment by fricoben** [comment]
This belongs to starknet quest repo

**Comment by fricoben** [comment]
Issue is now here https://github.com/starknet-id/starknet.quest/issues/454
