### ISSUE TITLE
No NFT yet on PFP setting design refactoring

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#654]
<img width="1103" alt="Capture d’écran 2024-01-23 à 17 28 15" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/a33d413c-59dd-44fa-b4ba-906d1498edb1">

This design is not good. 

1/ Text is too small we don't see it when it should be the first info of the page 
2/ We don't understand that the collections after are the whitelisted one

**Comment by Kevils** [comment]
Loom : https://www.loom.com/share/7c8e888381304c85aa7e84d680e9e413

Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=2795%3A26210&mode=design&t=xqn8PBigAmKC6zRP-1
