### ISSUE TITLE
Link Subscription Newsletter

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#657]
## Description

We would like to create a link to subscribe to the Starknet.id newsletter.

**Comment by fricoben** [comment]
It's a good idea. On the page, we want to:
- Show the benefits of the Newsletter I would say `All important Starknet Airdrops, Opportunities and news in your curated` or something like this
- Have a simple and cool design without scroll
- Once the guy fills the form we have a confirmation page asking him to put us out of his spam with a clickbait title like `One last thing...`, an image/GIF showing how to do it on gmail, and a call to action that opens his default mail app.

Waiting for your designs here @Kevils !

**Comment by Kevils** [comment]
Loom : https://www.loom.com/share/edae80a2e929469b944f24e4af251c7c

Figma : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=2788%3A23083&mode=design&t=4JpBqcGv9HFNXDpR-1
