### ISSUE TITLE
Potential broken link on Github

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#658]
**Describe the bug**
When I want to click on app.starknet.id on Github, I have got an error message.

**Screenshots**

https://www.loom.com/share/29f2ba865b824c5c959443b8d5191fc4?sid=957cf6a7-2d73-48ba-a968-72f887280559

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome

**Smartphone (please complete the following information):**

- Device: iOS
- Browser: Safari

**Comment by fricoben** [comment]
Yep closed
