### ISSUE TITLE
Duck not showing for ismael

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#659]
![telegram-cloud-photo-size-4-5911329520491807008-w](https://github.com/starknet-id/app.starknet.id/assets/78437165/5accf3c8-fb7d-4748-a70d-58ed6cf54698)

NFT ==> https://unframed.co/item/0x04fa864a706e3403fd17ac8df307f22eafa21b778b73353abf69a622e47a2003/1104261015105232229906782972232381340072622759644391366094079544993236647939

Address ==> 0x003b1b63Fff539BE8731EDb0e65Dd2C887c71ADCd6cFc6C9D9023570ACE7143A

**Comment by Marchand-Nicolas** [comment]
Starkscan doesn't have the Ismael NFT's data, including its image URL, so we cannot display it. It might have happened if the Brick API was down at the time of the mint. So, it's not an issue on our side, but we could ask Starkscan refresh the NFT, or find another way to display the NFT image when not available

**Comment by Marchand-Nicolas** [comment]
Refreshed NFT on starkscan
