### ISSUE TITLE
Add a mean to disabled subscription when a domain is transferred 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#671]
<img width="695" alt="Capture d’écran 2024-02-17 à 00 13 43" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/c38f4873-0330-401b-af6f-5c0949ac9c62">

my address: 0x0603d293356b3896546c741a22e7f81625b0ac5ee283d09883e79aa65e2d77ad
transaction auto renew: https://starkscan.co/tx/0x05874022e5a72322bf96c1222a1020e757acb35fbaeb230d297f092360c530da

**Comment by fricoben** [comment]
It happens to only a few people that tried to scam us and ask for a refund.

I'm not sure it's worth it to put in the UI and add noise to people that send their domain to one of their other wallets (it's almost impossible to make the difference between sell and transfer with something simple)

We'll keep it with the current tuto we have https://lfg-labs.notion.site/Disable-subscription-for-a-sold-domain-f7feea21afd148e58e4d473af9df20fb?pvs=74

**Comment by Kevils** [comment]
We finnaly added a tutorial : https://lfg-labs.notion.site/Disable-subscription-for-a-sold-domain-f7feea21afd148e58e4d473af9df20fb
