### ISSUE TITLE
Manage token STRK/USD

### ISSUE THREAD

**Issue by Kevils** [starknet-id/app.starknet.id#677]
We added a new select on the registration page. It allows the user to select the token they wish to pay with.

Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=2793%3A14047&mode=design&t=xqn8PBigAmKC6zRP-1

**Comment by ktarun1419** [comment]
Hi @Kevils  i want to work on this issue
