### ISSUE TITLE
Create separate collection for Starkuabu PFP  

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#679]
![image](https://github.com/starknet-id/app.starknet.id/assets/55296770/0df5cd26-0643-411b-9e64-864c76b38628)
 A separate collection for starkurabu to set is as PFP 
 With element / unframed collection link to **GET YOUR NFT** :
 
 https://element.market/collections/starkurabu
 https://unframed.co/collection/0x03ab1124ef9ec3a2f2b1d9838f9066f9a894483d40b33390dda8d85c01a315a3

**Comment by ktarun1419** [comment]
Hi @revengexd  is this issue still relevant?

**Comment by fricoben** [comment]
I would say we can replace StarkGuardians by Blobbert and StarkPunk by Starkurabu @Marchand-Nicolas
