### ISSUE TITLE
User domain is not showing in our website 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#682]
User address : 0x05188d1f186df7246561924d379c9efbe34add7d4c4d86b10711a250aaca15d1

Transaction hash for domain mint :
https://starkscan.co/tx/0x7de7fdc3dd060ddc067e22b4ad45730a9cf8f004049657761fb30b36d83a140
https://starkscan.co/tx/0x3267d1f17e5b6949b4867241d15146fc206eea73b45391a1c1e88eb9b6d7a5c

While in starkscan your data show's perfectly alright
![image](https://github.com/starknet-id/app.starknet.id/assets/55296770/fd152d76-933b-4d9b-bf68-39251d433f4a)

while in our website it show's different NFT picture and different address 
![image](https://github.com/starknet-id/app.starknet.id/assets/55296770/65234b41-8b58-41f2-894c-ac5b15fcf36d)
![image](https://github.com/starknet-id/app.starknet.id/assets/55296770/a849c4f5-6fc3-4386-80c4-6c1abd6e8f20)

Discord ticket :https://discord.com/channels/1025416762835095674/1214300628034129990

**Comment by fricoben** [comment]
Should be fixed now
