### ISSUE TITLE
Create Community Discounts for Domains

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#685]
## Description

In order to expand our community and onboard committed people, it would be great to set up a system where we can create discounts/free domains to distribute at events (with or without our presence) or to specific communities. To do this, we would need to be able to easily create a coupon containing:

- A maximum claim date
- A limited number of domains to claim
- A list of participants to whitelist only those present at the event (for large events like StarknetCC, for example, as it's more complicated for meetups)

Other suggestions are welcome!

**Comment by jrmncos** [comment]
hey! is this already closed on this one: https://github.com/starknet-id/app.starknet.id/issues/791 or there is something else to do?
