### ISSUE TITLE
Error while verifying twitter / discord  

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#696]
User using Argentx wallet in browser 

![image](https://github.com/starknet-id/app.starknet.id/assets/55296770/3ee01bf1-5ed6-4358-aa3b-cb580b7277de)

Error message :

Error in the called contract (0x06d5434f55a07bb1d5e4b583194e6b351c9004816414b8e6b0a6fd187b77c020): Error at pc=0:15647: Got an exception while executing a hint. Cairo traceback (most recent call last): Unknown location (pc=0:233) Unknown location (pc=0:5191) Unknown location (pc=0:11307) Error in the called contract (0x07d14dfd8ee95b41fce179170d88ba1f0d5a512e13aeb232f19cfeec0a88f8bf): Error at pc=0:1307: Got an exception while executing a hint: Execution failed. Failure reason: 0x4661696c656420746f20646573657269616c697a6520706172616d202331 ('Failed to deserialize param #1'). Cairo traceback (most recent call last): Unknown location (pc=0:101) Unknown location (pc=0:631) Error in the called contract (0x05dbdedc203e92749e2e746e2d40a768d966bd243df04a6b712e222bc040a9af): Execution failed. Failure reason: 0x4661696c656420746f20646573657269616c697a6520706172616d202331 ('Failed to deserialize param #1').

Ticket link : https://discord.com/channels/1025416762835095674/1218272581338005544

similar tickets with same issue :
https://discord.com/channels/1025416762835095674/1219630352340090961
https://discord.com/channels/1025416762835095674/1218192577723895959
https://discord.com/channels/1025416762835095674/1218272581338005544

**Comment by Marchand-Nicolas** [comment]
Fixed (env variables)
