### ISSUE TITLE
Open source frontend integration

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#708]
## Description 

We want to integrate domains and PFPs where they are relevant to be integrated. The easy win and most useful thing would be to integrate names everywhere a wallet address is shown to the user and PFPs in connection buttons for it to make sense. Based on each repo we will adapt the method used (check all methods https://docs.starknet.id/)

You have several choices: 
- Starknetid.js
- Starknet React
- Starknet.js
- API 

Up to you to choose the best method on each repo, imo the best will be to use the library they are already using !

## Front-end to contribute by priority order 

- [x]  https://github.com/argentlabs/Starknet-Scaffold/issues/38

- [x] JediSwap V1 and V2
https://github.com/jediswaplabs/jediswap-interface 
https://github.com/jediswaplabs/jediswap-v2-interface
https://github.com/jediswaplabs/jediswap-v2-interface/issues/194

- [x] https://github.com/dojoengine/dojo.js/issues/167

Dojo is a dev-tooling ecosystem for on-chain game son Starknet. They have premade indexers, premade contracts and premade front-ends. We want to add in the premade front-end the profile resolving (name and PFP). 

https://github.com/dojoengine/dojo.js

Update: this is already implemented in starknet react, so not applicable to dojo.js.

- [ ] https://github.com/layerswap/layerswapapp/issues/879
LayerSwap
https://github.com/layerswap/layerswapapp/tree/dev/pages

- [x] https://github.com/BibliothecaDAO/loot-survivor/issues/573 
Loot survivor
https://github.com/BibliothecaDAO/loot-survivor

- [ ] https://github.com/10k-swap/10k_swap-frontend/issues/4
https://github.com/10k-swap/10k_swap-frontend

- [x] https://github.com/ArkProjectNFTs/bridge/issues/217
- [x] https://github.com/Quantum3-Labs/scaffold-stark-2

**Comment by Oshioke-Salaki** [comment]
Can i have this?

**Comment by Jemiiah** [comment]
can I work on this

**Comment by Joy-Adah** [comment]
Hi @fricoben I'll love to work on this

**Comment by fricoben** [comment]
Well seems mostlt done
