### ISSUE TITLE
Restrict Sales of STARKURABU NFTs with removed/deleted traits

### ISSUE THREAD

**Issue by 00xUnknown** [starknet-id/app.starknet.id#713]
I suggest adding a feature which would prevent the listing or sale of NFTs on marketplaces if the previous owner has removed the previous traits that was minted with the NFT. This enhancement aims to protect buyers from purchasing NFTs that has been altered in a way that could be misleading.

**HOW I THINK IT WOULD WORK**
Implement a validation check that examines the metadata of NFTs during the listing or sale process. If the metadata indicates that traits have been removed compared to the original minted NFT, prevent the listing or sale from proceeding and provide a clear error message to the user.

Benefits
- it protects buyer from purchasing NFTs that have been altered in a misleading manner.
- it will preserve the value and integrity of NFTs within the project's ecosystem.
- it demonstrates a commitment to maintaining a fair and transparent marketplace for NFTs.

Implementation Details
- introduce a metadata validation step during the listing or sale process.
- compare the metadata of the NFT being listed/sold with the metadata of the original minted NFT.
- if discrepancies are found (e.g., traits have been removed), prevent the listing or sale and provide an error message explaining the issue.

**Comment by fricoben** [comment]
Appreciate the suggestions but this repo is not the right place to create an issue regarding Starkurabu :/ (Starkurabu repo is not public).

We can continue this discussion on Starkurabu discord :)
