### ISSUE TITLE
Indexer doesn't see when someone subscribed or not

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#714]
## Desc

We have several users on Discord complaining that they can not disable their subscription, I verified and they are in fact subscribed buit the `disable subscription` button doesn't appear

## Tickets

https://discord.com/channels/1025416762835095674/1224299245658439691
https://discord.com/channels/1025416762835095674/1224280648450310214

**Comment by irisdv** [comment]
Fixed by https://github.com/starknet-id/app.starknet.id/pull/715
