### ISSUE TITLE
When asked to set a pfp, it shows starknetids instead of starkurabus

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#729]
![image](https://github.com/starknet-id/app.starknet.id/assets/41830259/5a9d3025-d305-4233-94fb-9754bffb8508)

I was expecting to see starkurabus here, starknetids should not be allowed

**Comment by irisdv** [comment]
Wrong metadata uri was provided when minting the test NFTs. Closing this as the feature works as expected.
