### ISSUE TITLE
Transfer domain is not UX friendly

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#73]
<img width="536" alt="Capture d’écran 2022-12-27 à 17 25 58" src="https://user-images.githubusercontent.com/78437165/209694116-fbd11d4d-3725-4cce-a032-a91f8c630ba3.png">

When I have no identities available I'm a bit stuck and I do not know what to do

**Comment by fricoben** [comment]
The cool thing here would be to simply send the NFT cause people don't understand the fact that you can switch from starknet id to starknet id

**Comment by fricoben** [comment]
**FINAL UPDATE ** 

Instead of an identity transfer, you'll simply need to do a Textfield that takes addresses and .stark domains + a button that will trigger three transactions in a multi-call : 

1) Send the NFT to the account needed
2) Change the resolved address to the address you're sending the NFT (Using `set_address_to_domain`).

The component `changeAddressModal.ts` could be an example of how to proceed. 

This PR is pretty easy and should be an onboarding PR for a new contributor !

**Comment by phklive** [comment]
I'll be glad to take on this one 👍🏽
