### ISSUE TITLE
Web Wallet integration seems to be broken

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#733]
Reported by Ismael from Argent, tested on firefox and Brave

![telegram-cloud-photo-size-4-5839255304930443259-w](https://github.com/starknet-id/app.starknet.id/assets/41830259/db45559d-d624-4cd4-9004-f2ba0409636e)

![telegram-cloud-photo-size-4-5839255304930443260-w](https://github.com/starknet-id/app.starknet.id/assets/41830259/5ea628cd-f3db-4668-8568-f3995f714bfc)

**Comment by irisdv** [comment]
The issue seems to happen when we use `useContractWrite` from starknet-react, Francesco will look into it this week.
