### ISSUE TITLE
Wallet not reconnecting after refreshing page in sepolia

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#738]
https://github.com/starknet-id/app.starknet.id/assets/55296770/6cbd1455-af30-4ae9-b768-581d93bfd546

Wallet not auto-connecting after refreshing page !

**Comment by irisdv** [comment]
Did you test with another wallet to check if it only happens with Argent ?
Which browser are you using ?

**Comment by revengexd** [comment]
Using brave browser , yes i have tested with both argentx and braavos wallet ..it happens for both wallets
