### ISSUE TITLE
PFP interchanging after mint of the second domain (from binance.stark to vintage.stark) in Sepolia

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#740]
https://www.loom.com/share/b009c0dbaf1147fab6a3a5ffd62c9ab4?sid=d3bfc0b2-a796-4513-839b-1068946ab7d4

**Comment by irisdv** [comment]
When you set a NFT as a pfp on a domain it will remove it from the previous domain. So I think in your case it's the expected behaviour

**Comment by fricoben** [comment]
Seems good then

**Comment by revengexd** [comment]
But why it show'a only one NFT as PFP available while i have other domains available for selecting as PFP @fricoben 
<img width="289" alt="Screenshot 2024-04-23 at 4 39 21 PM" src="https://github.com/starknet-id/app.starknet.id/assets/55296770/784c8474-a281-44eb-abf5-02afd5ca8ff7">
<img width="289" alt="Screenshot 2024-04-23 at 4 40 32 PM" src="https://github.com/starknet-id/app.starknet.id/assets/55296770/e6cdda07-09c4-434c-b016-fb2d1b328c45">

it always show's the same NFT as available for PFP ( Green one )

**Comment by irisdv** [comment]
Because this NFT is actually a Starkurabu NFT but it was minted with the wrong metadata, so it looks like an identicons from starknet Id when it is in fact a starkurabu from the starkurabu sepolia contracts

**Comment by revengexd** [comment]
Thanks for the clarification :)
