### ISSUE TITLE
PFP selection step is missing during minting domain !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#762]
I have encounter 2 errors in pfp step , 
some times it direct's to checkout step instead of PFP selection &
In other case PFP selection step is not even shown in mint page 

Please check BOTH videos for clarification 
Thank you 

https://www.loom.com/share/2ca22fc8e3a14958a2e46859aaf712e9
https://www.loom.com/share/3df4db192f5145d4be664c1bf3b2f209

**Comment by fricoben** [comment]
Any explaination @irisdv ? Seems he has eligible NFTs in his wallet :)

**Comment by irisdv** [comment]
If you wait a bit more before going from step 1 to 2, does it work @revengexd ? I think sometimes it takes a bit of time to fetch the NFTs (they are fetched when you arrive on step 1). 
I could check if they are loaded before enabling the button ?

**Comment by revengexd** [comment]
@irisdv I have tried bit waiting while at step 1 , still it redirects me to step 3 ( checkout ) 
Sometimes after multiple refreshes and going back and forth , it takes me to PFP section !
