### ISSUE TITLE
Different renewal dates showed

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#767]
<img width="996" alt="Capture d’écran 2024-05-10 à 16 31 57" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/c3018a15-15d7-4373-8b52-fd02147c8c03">

**Comment by ibsule** [comment]
Can I hop on this hop on this?

**Comment by raizo07** [comment]
Hello @fricoben I'd like to work on this.

**Comment by Marchand-Nicolas** [comment]
Fixed
