### ISSUE TITLE
Optimize conversions: smart option to reduce duration

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#773]
If the user doesn't have enough token to pay because they chose too long a period (e.g., 5 years), offer to reduce it (currently, the flow is quite bad, especially on mobile, you have to reload the page to start over).

**Comment by Kevils** [comment]
figma : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3226%3A12794&t=dLPsldlQqmAYwuJK-1
