### ISSUE TITLE
Some bug animation

### ISSUE THREAD

**Issue by Kevils** [starknet-id/app.starknet.id#782]
<img width="1440" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/144677881/39e1518e-d211-4bba-942c-9bac6026d5ed">
The color of the input when it is focused is buggy; it has a gray background and an icon surrounded by white. We should keep the original input background and just change the text to dark.

<img width="1440" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/144677881/815d6f4e-44b7-4ac7-a01d-acdcf14eb133">
The button is disabled, but we have this hover interaction. Normally, there shouldn't be a hover animation on a disabled button.

<img width="1440" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/144677881/f0b7b1b0-b716-4352-9447-fccb2e8fcf98">

Same here

**Comment by fricoben** [comment]
This is fixed
