### ISSUE TITLE
Disable popup closing when clicking in the shadow when the wallet is opened

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#783]
When Argent or Braavos wallet is opened I sometimes missclick and click on the shadow, which closes the popup, but I can still send the transaction and I don't get feedback. Instead I shouldn't be able to close a popup via a click on the shadow while the wallet is opened.

**Comment by fricoben** [comment]
We can't reproduce the bug with @irisdv. Doesn't close for me on both wallets so maybe it closed for you because you're using several screens ? 

For such a tricky situation, please use loom to make a video :)
