### ISSUE TITLE
Domain gift page

### ISSUE THREAD

**Issue by Kevils** [starknet-id/app.starknet.id#791]
Figma : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3277%3A21682&t=dLTJNxOuLo2AclvY-1

This design is inspired by our last Quantum Leap campaign. We've reused the Quantum Leap template and adapted it for this one.
If you want to see what i mean : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=2474%3A41261&t=dLTJNxOuLo2AclvY-1

**Comment by fricoben** [comment]
the contract to connecit it to https://github.com/starknet-id/domain_gift_contract

**Comment by jrmncos** [comment]
hey team! I would like to work on this one (:
