### ISSUE TITLE
`Disable subscription` button should disable both tokens subscription

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#812]
## Desc

If I have two tokens subscribed and I click on disable the subscription, I'm not sure we disable also for STRK I think we only do so for ETH. We need to disable both. We can do this using `useNeedSubsription` to know if a user is subscribed and to what currencies.

**Comment by irisdv** [comment]
`Disable subscription` already disables all existing subscriptions for all tokens.
