### ISSUE TITLE
On buying a domain with STRK I have an invalid signature

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#814]
On buying a domain with STRK I have an invalid signature
<img width="376" alt="Capture d’écran 2024-06-02 à 18 42 25" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/387128d5-d576-49ad-9add-a64a8f224414">
<img width="351" alt="Capture d’écran 2024-06-02 à 18 43 45" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/afec1165-dd6a-4410-9d55-37d426584145">

**Comment by irisdv** [comment]
The contract was missing the public key to verify the signature. It's fixed now.
