### ISSUE TITLE
Argent 1$ domain page

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#821]
## Description 

Create a special page for [this](https://www.notion.so/lfg-labs/Argent-x-Starknet-ID-Discount-0bfb0faa247e42499bc5e5542622907e) campaign using the `quantum-leap` campaign. (you can reuse `quantumleap.tsx` and change the wording°.

We need to have: 
- Available only to Argent wallets (mobile and extension)
- Domain costs 1$ for 3 months
- Add argent.stark as a referee on the page directly
- Possibility to subscribe (optional) 
-  24/06-02/07 
- No upsell so you can delete it from `quantumleap.tsx`
- Discount needs to be created on-chain you can ask @Th0rgal for sepolia :)

All campaigns infos here https://www.notion.so/lfg-labs/Argent-x-Starknet-ID-Discount-0bfb0faa247e42499bc5e5542622907e

**Comment by Th0rgal** [comment]
<img width="355" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/be69242c-4a48-4de2-9507-6c16530d1cec">
@fricoben I need your signature
