### ISSUE TITLE
After choosing an avatar, the modal is not closed automatically

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#824]
I confirmed the tx in argent but the modal stayed instead of confirming me, a user might end up sending the transaction multiple times.

<img width="1464" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/9a79a60b-ae92-4a9a-b22d-6c604f4a3a2e">

Note: it should go directly to the id customization page

**Comment by Marchand-Nicolas** [comment]
Will be fixed with starknet react v3
