### ISSUE TITLE
free registration image is blurry

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/app.starknet.id#825]
<img width="1148" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/41830259/49dbc605-8fc8-4b16-8aca-99a50e113c03">

We need a better quality image

**Comment by Crosstons** [comment]
I want to work on this one.

**Comment by TEMHITHORPHE** [comment]
this should be closed, seems fixed.

**Comment by fricoben** [comment]
was closed
