### ISSUE TITLE
Go to your identity after registration skeleton

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#860]
This video shows the feedback after the registration from the UI is strange when I click on `go to your domain`. The tx is taking long time so that's the issue that sould be fixed soon by Starknet itself, but our way of showing the loading with skeleton makes me think of a bug so I would prefer to make the skeleton better (not only the PFP loadding but all the part of the card with their associated skeleton too and maybe a message with it).

https://www.loom.com/share/c034501fb976404ea9d9794774b0611b

**Comment by Kevils** [comment]
Regarding the skeleton to be implemented on the identity card, I suggest we:

- Use a loading skeleton for each element that makes up the card: https://mui.com/material-ui/react-skeleton/
- Add a "refresh" button to refresh the page and display the identity elements. We can use the structure of the image below as an example, with the card loading with skeletons on the left and a refresh button on the right, along with a title and subtitle to inform the user that if the content does not appear, they can refresh the page.
![Screenshot 2024-07-22 at 10 08 55](https://github.com/user-attachments/assets/cc252946-2c11-4e94-80fa-d501c6e7458f)
