### ISSUE TITLE
Application error - gift page

### ISSUE THREAD

**Issue by sdaav** [starknet-id/app.starknet.id#868]
**Describe the bug**
When people try to registrer a domain for free through Argent Mail/Argent Mobile, they encountered an issue with a client-side error, like on the screenshot below. Maybe need to precise on the gift page that people need to use Argent X extension.

Otherwise, it's working well with Braavos.

![5884068392401487121](https://github.com/user-attachments/assets/83c9a3bd-1bf6-4942-91d2-3ab6077ce650)

**Comment by sdaav** [comment]
> **Describe the bug** When people try to registrer a domain for free through Argent Mail/Argent Mobile, they encountered an issue with a client-side error, like on the screenshot below. Maybe need to precise on the gift page that people need to use Argent X extension.

Otherwise, it's working well with Braavos.

> 
> ![5884068392401487121](https://private-user-images.githubusercontent.com/57441909/356190078-83c9a3bd-1bf6-4942-91d2-3ab6077ce650.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzY1OTMsIm5iZiI6MTcyMzEzNjI5MywicGF0aCI6Ii81NzQ0MTkwOS8zNTYxOTAwNzgtODNjOWEzYmQtMWJmNi00OTQyLTkxZDItM2FiNjA3N2NlNjUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2NTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YzI1MDQwMzE2ZTE5OWYxMDRiMTY3YWJkMjFkODIyNGFiOWY2YjZlYWRhNGRhMmVlMDdhZDRlYjRhZjZjZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ls037tBHL4Vcn-YYCZCTOcyJr88_LGWP-YeSUlYCMKQ)

**Comment by fricoben** [comment]
was an argent mail bug we fixed
