### ISSUE TITLE
TxConfirmationModal does not display correct transaction hash after disableRenewal method is called

### ISSUE THREAD

**Issue by YanYuanFE** [starknet-id/app.starknet.id#883]
Bug Description:
When the disableRenewal method is called, the TxConfirmationModal pops up, but the corresponding txHash is not set correctly. This results in the transaction hash not being displayed in the modal, causing confusion for the user.
Steps to Reproduce:
1. Trigger the disableRenewal method by clicking the "DISABLE SUBSCRIPTION" action.
2. Observe that the TxConfirmationModal pops up.
Notice that the transaction hash (txHash) is not displayed in the modal.
Expected Behavior:
The TxConfirmationModal should display the correct transaction hash (txHash) when the disableRenewal method is called.
Actual Behavior:
The TxConfirmationModal pops up without displaying the correct transaction hash (txHash).

**Comment by fricoben** [comment]
<img width="222" alt="Capture d’écran 2024-09-23 à 15 20 43" src="https://github.com/user-attachments/assets/556258c6-c9fb-4ae6-b6e4-9d5dbf28ec69">

true this link is set to https://sepolia.starkscan.co/tx/undefined
