### ISSUE TITLE
Impossible to set as main domain for legacy

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#891]
Impossible to set as main domain for legacy here is the [ticket](https://discord.com/channels/1025416762835095674/1288040603174834218)

<img width="937" alt="Capture d’écran 2024-09-26 à 18 54 56" src="https://github.com/user-attachments/assets/708dc134-0bd2-4d41-9b65-b01581dcaf77">

![image](https://github.com/user-attachments/assets/438309cc-15db-4c22-b710-0adb9715013d)

**Comment by Marchand-Nicolas** [comment]
Fixed the indexers
