### ISSUE TITLE
Change `404.tsx` image

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#911]
## Description 📹

Our current error illustration is used for `404.tsx` when it's not expressive for the 404 situation so I created a dedicated `404illu.webp` image that you can find here that need to replacte the current `errorIllu.webp`

[404.zip](https://github.com/user-attachments/files/17764401/404.zip)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	
- [ ] Change `errorIllu.web` to `404illu.webp` in `404.tsx`

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Jonatan-Chaverri** [comment]
Hello! I will like to contribute with this issue! This is my public onlydust profile https://app.onlydust.com/u/Jonatan-Chaverri

**Comment by 0xdevcollins** [comment]
Can I work on this, please?

**Comment by Villarley** [comment]
hi @fricoben 🚀,
I’m Santiago Villarreal, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon, Buildathon, for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

For this issue, I’ll replace the current errorIllu.webp with the newly provided 404illu.webp in 404.tsx to ensure the illustration aligns better with the situation. I'll commit to the project structure and deliver the solution in the estimated time with the estimated quality. I already contributed to other projects of lfglabs with a successful journey.
Pls feel free to reach out anytime!

**Comment by PedroCo3lho** [comment]
Can I work on this task?
ETA 1 hour

**Comment by vestor-dev** [comment]
Hey @fricoben please let me handle this issue :)
I would like to contribute to this repo
Eta: 2hrs

**Comment by abdegenius** [comment]
I can comfortably handle this issues

**Comment by Steph3097** [comment]
Hello! My name is Sttef and i have over 5 years of experience in front end development, with experience on typescript, react, javascript and using tools like figma and zeplin

I’m part of the Dojo team ⛩️

I would like to be part of this issue! I will change the image as requested and follow the steps you mentioned! 

Thank you!

**Comment by TheSQLguy** [comment]
gm @fricoben, i have skills in python, js and ts, and i am a newcomer here. I'd love to start my journey with od :)

**Comment by TheSQLguy** [comment]
gm @fricoben, i have skills in python, js and ts, and i am a newcomer here. I'd love to start my journey with od :)

**Comment by TheSQLguy** [comment]
gm @fricoben, i have skills in python, js and ts, and i am a newcomer here. I'd love to start my journey with od :)

**Comment by starknetbrother** [comment]
I'm a new contributor and would love to work on this

**Comment by TheSQLguy** [comment]
gm @fricoben, i have skills in python, js and ts, and i am a newcomer here. I'd love to start my journey with od :)

**Comment by 0xLemonn** [comment]
i am a backend dev adept in js,ts and python, a newcomer here, and willing to contribute.

**Comment by 0xLemonn** [comment]
i am a backend dev adept in js,ts and python, a newcomer here, and willing to contribute.

**Comment by Akshola00** [comment]
Can I take this from here?

**Comment by Unickhub** [comment]
I’d like to work on this.

**Comment by josephchimebuka** [comment]
Mind if I take this issue?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Yunusabdul38** [comment]
I’d like to resolve this.

**Comment by Thibrac** [comment]
I'd be happy to do this.

**Comment by Steph3097** [comment]
Hello! My name is Sttef and i have over 5 years of experience in front end development, with experience on typescript, react, javascript and using tools like figma and zeplin

I’m part of the Dojo team ⛩️

I would like to be part of this issue! I will change the image as requested and follow the steps you mentioned! 

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You 
ETA : 48 hours

**Comment by SudiptaPaul-31** [comment]
Will love to work on this issue.

My approach to tackle this issue:

Will check first both the error images present and then will check at where its being rendered and will eventually remove the older one and add the new one and check that if its working properly or not and finally end by making a pr.

ETA-1Day

**Comment by Benjtalkshow** [comment]
Can I contribute to this one?

**Comment by ShantelPeters** [comment]
Could I take a shot at this?

**Comment by Michaelkingsdev** [comment]
Can I handle this task?

**Comment by GideonBature** [comment]
Would love to tackle this!

My name is Gideon Bature, a Software Engineer with experience using TypeScript/JavaScript with ReactJS. If assigned this issue, I will send my first PR within 48 hrs. 

Thank you!

**Comment by 0xDeon** [comment]
I’m interested in this one.
I can have this delivered in 24 hrs

**Comment by Ekene001** [comment]
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

To tackle this issue, I will replace the current error illustration used for the 404 error page with the new, more expressive 404illu.webp image you provided. I will start by identifying the location of the current errorIllu.webp image within the project and then ensure that the new image file is correctly placed in the appropriate directory.

Next, I will update the 404.tsx page to reference the new 404illu.webp image instead of the old one. This will involve updating the image source path and ensuring the styling aligns with the design of the new illustration. I will also double-check that the new image is responsive and properly displayed across different screen sizes.

After implementing the changes, I will test the 404 error page to ensure the new image is correctly displayed when a 404 error occurs and verify that no other parts of the page are affected by this update.

**Comment by melnikga** [comment]
I'd like to take this issue.
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by morelucks** [comment]
Let me try this one!

**Comment by OWK50GA** [comment]
May I pick this up?

**Comment by imoleayomi19** [comment]
May I handle this issue? Yes
I am a Front-end developer. I am proficient in CSS, Typescript, JavaScript, Solidity.
I would love to work on this project.

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.


i will remove and add the newly proposed image for the 404 page and if possible, add animation 

Thanks

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️. This looks like a straightforward and fun task to work on, and I’d love to take it on. I’m detail oriented and familiar with making targeted updates like this, so I’m confident I can handle it smoothly.

My workflow:

- Replace errorIllu.webp with 404illu.webp in 404.tsx.
- Test to ensure functionality remains intact.
- Commit changes with a clear message.
- Follow PR guidelines for submission and review.

ETA: 24 hrs

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by Supa-mega** [comment]
Could I take a shot at this?

**Comment by Emmanex01** [comment]
Hi, I’m interested in this one. Would you mind assigning it to me.

**Comment by sandragcarrillo** [comment]
Is it okay if I take this?

**Comment by sandragcarrillo** [comment]
I would love to contribute to this issue, I have experience as a frontend developer.

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by t0fudev** [comment]
Hello! My name is t0fudev, and I am a computer science student, a Dojo Coding member and a Web3 developer with some experience working on the frontend of different projects. I am eager to apply my skills and contribute to this amazing project. 

I would work on this issue by following the required process according to the project's description in order to make the change with the corresponding image ensuring that it works correctly. And if there's any doubt I would ask inmmediately to maintainers for help.

I would be honored to contribute to this issue and make a meaningful impact on the project. Thank you for considering my application and I sincerely appreciate your time and the opportunity.

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, 
I would love to get assigned with this issue
