### ISSUE TITLE
Add PFP collections recommendations

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#912]
## Description 📹

In `constant.ts` and the `NftCollections` const we have only two collection recommendations we need to add more

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
Please add images and title for these collections: 
- [ ] https://element.market/collections/starkpunks
- [ ] https://element.market/collections/personaxar
- [ ] https://element.market/collections/alternovaxyz
- [ ] https://element.market/collections/ventorians-nft-collection
- [ ] https://element.market/collections/everai-starknet
- [ ] For each collection make sure it renders right on the https://app.starknet.id/pfpcollections page

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by KevinLatino** [comment]
Let me try this one!

**Comment by KevinLatino** [comment]
Hello @fricoben!

My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

Here is my plan:

I’ll update the NftCollections constant by adding the name, imageUri, and externalLink properties for the collections: StarkPunks, PersonaXar, AlternovaXYZ, Ventorians NFT Collection, and Everai Starknet. I’ll make sure each collection renders correctly on the pfpcollections page, and if needed, I can add a test case for validation.

**Comment by NueloSE** [comment]
@fricoben kindly assign me this issue

**Comment by petersdt** [comment]
@fricoben  can i take on this issue when odhack starts 

ETA <= 24hrs

**Comment by CollinsC1O** [comment]
Hello @fricoben I'm a front-end and a blockchain developer I’d like to resolve this.

**Comment by Unickhub** [comment]
Is it okay if I take this?

**Comment by abdegenius** [comment]
May I take care of this?

**Comment by Akshola00** [comment]
Can I handle this task?

**Comment by josephchimebuka** [comment]
Could I take over this issue?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Unickhub** [comment]
Could I be assigned to this?

**Comment by Benjtalkshow** [comment]
Could I take a shot at this?

**Comment by ShantelPeters** [comment]
Could I take a shot at this?

**Comment by Michaelkingsdev** [comment]
Could I grab this task?

**Comment by jimenezz22** [comment]
GM! Can I help with this issue? I’m part of the Dojo Coding Community and have experience in frontend development, including working with components, rendering, and ensuring smooth functionality

**Comment by Ekene001** [comment]
Hi, Could i be assigned to this issue? I'm a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

**Comment by melnikga** [comment]
I'd like to take this issue.
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by Emmanex01** [comment]
Is it okay if I tackle this?

**Comment by SudiptaPaul-31** [comment]
Would love to solve this issue

**Comment by abdegenius** [comment]
@fricoben I have made a PR on this please check and review, can't update the label to 'ready for review' tho couldn't find the section(pretty weird). But the PR meets all the specified requirements and i checked it thoroughly before making the PR. Thank you!
