### ISSUE TITLE
Change github link everywhere it needs to be changed

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#913]
## Description 📹

Our old github link is broken (https://github.com/starknet-id) please change it to https://github.com/lfglabs-dev

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	
- [ ] Change github link everywhere it needs to be changed

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by lauchaves** [comment]
Hey I’m Lau Chaves from dojo coding Costa Rica, id love to contribute to this project, may I give this one a try ?

**Comment by omsant02** [comment]
i would like to work on this issue @fricoben 
i am a new contributor for this repo and want to start my journey with starknet.quest

thank you

**Comment by abdegenius** [comment]
I can comfortably handle this issues

**Comment by 0xOlivanode** [comment]
I'd be happy to do this.

**Comment by Steph3097** [comment]
Hey! I’m Sttef! i have experience in front-end development! 

I’m part of the dojo ⛩️


It would be a pleasure to work and participate on this one! I will change all the links to the one that you preferred, can i give it a try? 

Thank you!

**Comment by codebestia** [comment]
Can I work on this, please?

**Comment by FemiOje** [comment]
gm. I'm jinius, a frontend web developer looking to make my forst contribution in this ODHack.

How I would approach this:
1. Fork the repo and create a fix-913 branch.
2. Replace all occurences of the old link (https://github.com/starknet-id) with new link (https://github.com/lfglabs-dev), eg in navbar.tsx, and in the readme
3. Test the new link and confirm it doesn'r break the app.
4. Create pull request.

I estimate this will take me 1 day.
Thanks, lfg

**Comment by starknetbrother** [comment]
Can I take care of this issue?

**Comment by Akshola00** [comment]
Could I grab this task?

**Comment by Unickhub** [comment]
Mind if I try this one?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Yunusabdul38** [comment]
Mind if I take this issue?

**Comment by Steph3097** [comment]
Hey! I’m Sttef! i have experience in front-end development! 

I’m part of the dojo ⛩️


It would be a pleasure to work and participate on this one! I will change all the links to the one that you preferred, can i give it a try? 

Thank you!

**Comment by jaykayudo** [comment]
Could i work on this?

**Comment by aurlic** [comment]
Hey ! I would love to give a go to this issue. I am new on OnlyDust and would love to start somewhere, and think this could be a good first issue. I am a student at school 42, and am currently learning Cairo through Node Guardians, and Rust. Thank you in advance !

**Comment by SudiptaPaul-31** [comment]
Will love to work on this issue.

ETA-1day

**Comment by Benjtalkshow** [comment]
Mind if I try this one?

**Comment by ShantelPeters** [comment]
May I handle this issue?

**Comment by Michaelkingsdev** [comment]
I’d like to help with this.

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in typescript and javascript, would love to work on this , my ETA is >12 Hours and ill create a draft PR in 10 hours time. Thank you for this opportunity. :)

**Comment by GideonBature** [comment]
May I be assigned to this?

My name is Gideon Bature, a Software Engineer with experience using TypeScript/JavaScript with ReactJS. If assigned this issue, I will send my first PR within 72 hrs. 

Thank you!

**Comment by martinvibes** [comment]
Can I take care of this issue?
i would love to work on this issue :)

**Comment by melnikga** [comment]
I'd like to take this issue.
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by imoleayomi19** [comment]
May I try my hand at this?Yes 
I am a Front-end developer. I am proficient in CSS, Typescript, JavaScript.
I would love to work on this project and solve the issue.

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.


Remove the github link and add the new where it is needed for a better connection of developers.

Thanks

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️ and Id love to contribute to this project. 

My workflow:

- Fork the repository and create a new branch named fix-913
- Update all occurrences of the old GitHub link https://github.com/starknet-id to the new link https://github.com/lfglabs-dev in all relevant files like navbar.tsx and the README
- Test the application to ensure the new links work correcylu
- Commit my changes and create a pull request, following the contribution guidelines

ETA: 24 hrs

**Comment by Amarjeet325** [comment]
Can I try solving this issue?

**Comment by ryzen-xp** [comment]
May I try my hand at this?

**Comment by OWK50GA** [comment]
Is it okay if I tackle this?

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by Emmanex01** [comment]
Hi, 
I would like to work on this?

**Comment by akintola4** [comment]
Can I take care of this issue?i would love to build it , this is my  twitter account for my works https://x.com/photofola , i would be happy if i am give this task for my first ever task on this platform

**Comment by vestor-dev** [comment]
Is it okay if I tackle this?
i'm a new timer on this project

**Comment by akintola4** [comment]
As a skilled React developer, I'm eager to contribute my expertise to this hackathon. My experience in building complex UI components, data-driven applications, and real-time updates has honed my ability to deliver efficient, scalable, and user-friendly web applications. I'm excited to collaborate with a talented team and leverage my problem-solving skills to tackle challenging problems and deliver innovative solutions.this is my  twitter account for my works https://x.com/photofola , i would be happy if i am give this task for my first ever task on this platform

**Comment by sandragcarrillo** [comment]
I would love to contribute to this issue, I was part of Nethermind internship and one of my main tasks was to make sure the documentation of Starknet related projects were up to date, so this issue would be an awesome opportunity to start my contribution to open source projects in the Starknet ecosystem.

**Comment by Kritto** [comment]
Is this issue still available?

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, 
I would love to get assigned with this issue
