### ISSUE TITLE
Delete old join the tribe files

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#914]
## Description 📹

**Remove the `JoinTheTribe` page and all related files, including images, components, and CSS that are only used for this page.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - [ ] **Delete the `jointhetribe.tsx` file**: This file is located in the `pages` directory.
   - [ ] **Remove related components/images...**: Identify and delete components that are only used in `jointhetribe.tsx`. 
   
   These include what you can find here
  
<img width="590" alt="Capture d’écran 2024-11-15 à 11 12 29" src="https://github.com/user-attachments/assets/a02ad639-f462-471a-b3d9-ad2eb06d0bfb">

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: Remove JoinTheTribe page and related files"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by 0xdevcollins** [comment]
Would love to tackle this!

**Comment by omsant02** [comment]
i would like to work on this issue @fricoben 
i am a new contributor for this repo and want to start my journey with starknet.quest

thank you

**Comment by vestor-dev** [comment]
Hey @fricoben can I have this issue I'm new

**Comment by abdegenius** [comment]
I can comfortably handle this issues

**Comment by Steph3097** [comment]
Hello! I’m Sttef! I’m part of the Dojo team ⛩️

I would like to take care and contribute on this issue, i will follow your guidelines and be sure that the changes doesn’t affect anything! 

Thank you!

**Comment by petersdt** [comment]
Could I take on this issue?

**Comment by aradix16** [comment]
Hello ! I'm Antoine from Santiago. This is my first ODHack, this issue looks pretty straightforward. I'm ready to work on . Thanks :)

**Comment by Akshola00** [comment]
I’d like to help with this.

**Comment by Unickhub** [comment]
Would love to tackle this!

**Comment by Yunusabdul38** [comment]
I'd love to work on this!

**Comment by pheobeayo** [comment]
May I be assigned to this?
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.
My Approach includes:
- Reviewing codebase.
- locating the JointheTribe page.
- deleting the JointheTribe page.
- Testing the code to avoid breakage.
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR

**Comment by Steph3097** [comment]
Hello! I’m Sttef! I’m part of the Dojo team ⛩️

I would like to take care and contribute on this issue, i will follow your guidelines and be sure that the changes doesn’t affect anything! 

Thank you!

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
May I take care of this?

**Comment by Michaelkingsdev** [comment]
I'd love to give this a go.

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in typescript and javascript, would love to work on this , my ETA is >6 Hours and ill create a draft PR in 3 hours time. Thank you for this opportunity. :)

**Comment by GideonBature** [comment]
May I handle this issue?

My name is Gideon Bature, a Software Engineer with experience using TypeScript/JavaScript with ReactJS. If assigned this issue, I will send my first PR within 48 hrs. 

Thank you!

**Comment by SudiptaPaul-31** [comment]
Can I take this issue?

**Comment by josephpdf** [comment]
Hi! @fricoben   
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Fork the Repository and Create a Branch:**
- Fork the repository and create a new branch using the issue number:
`git checkout -b fix-[issue-number]`
2. **Implement Changes:**
- Delete the `jointhetribe.tsx` file located in the `pages `directory.
-Identify and delete related components, images, and CSS files that are only used in `jointhetribe.tsx.`
3. **Run Tests and Commit Changes:**
- Ensure your changes do not break existing functionality.
- Commit your changes with a clear message:
`git commit -m "Fix: Remove JoinTheTribe page and related files"`
4. **Follow Contribution Guidelines:**
- Make sure you are assigned to the issue before creating a pull request.
- Complete the task within 3 business days.
- In your PR description, close the issue by writing `Close #[issue_id].`
5. **Review Process:**
- Submit your PR and change the label to “ready for review”.
- Address any requested changes and update the label back to “ready for review” once done.
- Test your PR locally before pushing and verify that tests and build are working after pushing.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️. I’d love to take on this task. Removing unused pages and files seems like a straightforward but important job, and I’m confident I can handle it efficiently while keeping everything clean and functional.

My workflow:

--Delete jointhetribe.tsx from the pages directory
- Remove related components, images, and CSS files
- Test to ensure no functionality is affected
- Commit and follow PR guidelines for submission

ETA: 24 hrs

**Comment by Amarjeet325** [comment]
Can I try solving this issue?

**Comment by ryzen-xp** [comment]
May I be assigned to this?

**Comment by Supa-mega** [comment]
Can I take this from here?

**Comment by mamicho16** [comment]
I'd like to help with removing the JoinTheTribe page and related components.

I'll do the next steps:

Remove 'jointhetribe.tsx' from the pages directory
Identify and remove all associated components, images, and CSS files that are exclusively used by this page
Ensure no other pages are affected by these removals

**Comment by vestor-dev** [comment]
Mind if I try this one?
i would love to

**Comment by Kritto** [comment]
Hi, have a perfect understanding of this task.

I will implement the appropriate changes, run tests and commit changes.

I have a software engineering background and I will deliver appropriately on time.

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by Emmanex01** [comment]
Hello, 
I’d like to help with this.

**Comment by GideonBature** [comment]
Will start working on this issue ASAP.
