### ISSUE TITLE
Argent Mobile not working

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#915]
## Description 📹

The Argent Mobile connection doesn't work on the Starknet ID website atm we have

![telegram-cloud-photo-size-4-5882024735292900841-y](https://github.com/user-attachments/assets/ac4c6c70-fa7e-4e90-90df-be744dda3d81)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

- [ ] Understand why no connectors are showing and fix it (make sure to test it's working with the build after pushing)

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by PedroCo3lho** [comment]
Hello @fricoben,
I’m a full-stack developer and have previously contributed to StarkQuest and the Starknet ecosystem. I’d like to handle this issue, please let me know, and I’ll start and deliver the solution asap.

**Comment by zintarh** [comment]
I'd love to give this a go.

**Comment by starknetbrother** [comment]
I'm a first time contributor and would love to work on this. I have vast knowledge on argent wallet

**Comment by abdegenius** [comment]
Mind if I take this issue? Would love to tackle this! I can comfortably handle this issues

**Comment by wheval** [comment]
Hello @fricoben, 

My name is Wheval. I'm a front-end developer and onlydust open-source contributor. I have experience with React, Next.js, TypeScript and starknetkit. I have also contributed to other projects on Starknet.

I would check the current implementation of the mobile connect wallet and reconfigure it with the `argentMobileConnector` method from StarknetKit using the right parameters. I would test it on my mobile devices to ensure it works as expected.

ETA is 2 days.

**Comment by Unickhub** [comment]
I will really love this issue, 
Could I take over this issue?

**Comment by JoE11-y** [comment]
May I be assigned to this?

**Comment by Benjtalkshow** [comment]
Can I take this issue?

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by MrRoudyk** [comment]
Can I take care of this issue?

**Comment by Michaelkingsdev** [comment]
Is it okay if I take this?

**Comment by Supa-mega** [comment]
May I pick this up?

**Comment by jedstroke** [comment]
May I take this issue on? I will deliver it in one piece in 3 business days 🙏🏽

**Comment by Emmanex01** [comment]
Hello Sir,
I would love to be assigned this issue.
