### ISSUE TITLE
On `/identities` I have expired domains that don't seem expired

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#924]
## Description 📹

On `/identities` I have expired domains that don't seem expired, when I click on them I can see clearly they are 👇

<img width="899" alt="Capture d’écran 2024-11-25 à 11 18 35" src="https://github.com/user-attachments/assets/ed060a34-7c37-4fa9-a7a6-8f20e14ab38b">

We need to add a warning label in red as we do with the `subscription` when a domain is expired to inform the user directly on `/identity`

## Proposed Actions 🛠️

Here's a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - [ ] Update the warning condition in IdentitiesGalleryV1 component:
   ```typescript:components/identities/identitiesGalleryV1.tsx
   // ... existing code ...
   {needAutoRenewal?.includes(identity.domain) && 
    (isIdentityExpired(identity) || isIdentityExpiringSoon(identity)) ? (
     <div className={styles.expiryWarning}>
       <Tooltip
         title={
           isIdentityExpired(identity)
             ? "This domain has expired! Renew it now to keep using it."
             : `This domain will expire on ${timestampToReadableDate(identity?.domain_expiry ?? 0)}`
         }
         arrow
       >
         <RebewalIcon color={isIdentityExpired(identity) ? "error" : "warning"} />
       </Tooltip>
     </div>
   ) : null}
   // ... existing code ...
   ```

This code exists right now but it doesn't work so please find out why (timestamp conversion problem or something else), moreover transform the warning (yellow) color in error (red) if it's expired).

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: Add distinct warning for expired domains"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren't assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by OWK50GA** [comment]
Hey, @fricoben
I can handle this issue, as the steps are stated clearly
I will implement the check to see whether or not the domain is expired or is expiring soon.
If these return true, I will implement the warning depending on which condition returned true, as shown above.

I will like to be assigned this issue

**Comment by tasneemtoolba** [comment]
Can I attempt this issue? read the proposed actions checklist and requirements, things are clear and straightforward

**Comment by PedroCo3lho** [comment]
Can I tackle this one?

**Comment by hoangkianh** [comment]
Would love to take this on. 💪

**Comment by Birdmannn** [comment]
Hi @fricoben 
Can I hope on this?

**Comment by Emmanex01** [comment]
Let me handle this issue!

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

# My Plan for Adding a Warning Label for Expired Domains

## 1. Create a Branch
I will fork the repo and create a branch for the issue:
```bash
git checkout -b fix-[issue-number]
```

## 2. Debug and Implement Changes

### Debug the Existing Code
I will identify why the current condition is not working, focusing on potential timestamp conversion issues. I will verify the following:
- Ensure `identity?.domain_expiry` is returning the correct timestamp.
- Confirm that the `timestampToReadableDate()` function is correctly converting the timestamp.

### Implement the Fix
I will modify the `IdentitiesGalleryV1` component to update the warning condition and fix the timestamp issue. Additionally, I will ensure the warning appears in **red** if the domain is expired. The corrected code will look like this:

```jsx
{needAutoRenewal?.includes(identity.domain) &&
 (isIdentityExpired(identity) || isIdentityExpiringSoon(identity)) ? (
  <div className={styles.expiryWarning}>
    <Tooltip
      title={
        isIdentityExpired(identity)
          ? "This domain has expired! Renew it now to keep using it."
          : `This domain will expire on ${timestampToReadableDate(identity?.domain_expiry ?? 0)}`
      }
      arrow
    >
      <RebewalIcon color="error" />
    </Tooltip>
  </div>
) : null}
```

### Key Fixes
1. Ensure `isIdentityExpired()` and `isIdentityExpiringSoon()` return accurate results based on `identity?.domain_expiry`.
2. Update the `RebewalIcon` color to `"error"` when the domain is expired.

## 3. Test Locally
I will ensure my changes work as expected and do not break existing functionality:
```bash
npm run build
npm run start
```

I will verify:
- Expired domains display a red warning with the correct expiration message.
- Domains close to expiration show a warning with the expected date.

## 4. Commit and Push
I will commit the changes with a clear message:
```bash
git add components/IdentitiesGalleryV1.tsx
git commit -m "Fix: Add red warning for expired domains in identities"
git push origin fix-[issue-number]
```

## 5. Submit PR
I will create a pull request referencing the issue:
```plaintext
Close #[issue_id]
```

## 6. Review and Finalize
I will label the PR as "ready for review," address feedback, and confirm all tests pass.

**Comment by Benjtalkshow** [comment]
Could I try solving this?

**Comment by MrRoudyk** [comment]
Can I take this issue?

**Comment by emarc99** [comment]
Is it okay if I tackle this? I will send screen as proof things work as expected.

**Comment by CEOliam** [comment]
May I pick this up?

**Comment by pheobeayo** [comment]
Could I take over this issue?

**Comment by Kingsuite** [comment]
Could I grab this task?

**Comment by NueloSE** [comment]
Would love to tackle this!

**Comment by mimisavage** [comment]
Could I be assigned to this?

**Comment by fricoben** [comment]
assigned @emarc99

**Comment by emarc99** [comment]
Thanks, just seeing this. Getting to work.

**Comment by emarc99** [comment]
@fricoben I sent a DM on Telegram.
