### ISSUE TITLE
New pricing image

### ISSUE THREAD

**Issue by Kevils** [starknet-id/app.starknet.id#927]
## Description 📹

**Insert the new pricing image on this page "https://docs.starknet.id/core/faq".**

File : [Pricing.png.zip](https://github.com/user-attachments/files/17901882/Pricing.png.zip)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Amarjeet325** [comment]
Could I take a shot at this?

**Comment by 3th-Enjay** [comment]
I'd love to work on this!

**Comment by 3th-Enjay** [comment]
I’d love to work on this task. I worked on the readme.md and I'm really excited about working on this project

**Comment by 3th-Enjay** [comment]
May I try my hand at this? I am confident in my ability to deliver quality 💯

**Comment by SudiptaPaul-31** [comment]
Can I start working on this?

**Comment by mayasimi** [comment]
Can I handle this task? ETA <= 10hrs

**Comment by 3th-Enjay** [comment]
Mind if I try this one?

**Comment by fricoben** [comment]
issue shouldn't be in this repo, I copied it here https://github.com/lfglabs-dev/docs.starknet.id/issues/57

@Kevils
