### ISSUE TITLE
Analytics page

### ISSUE THREAD

**Issue by Kevils** [starknet-id/app.starknet.id#931]
## Description 📹

The Starknet ID analytics page will be available to all users. You can see the Total number of domain names registered on Starknet ID since launch, and Total number of subdomains created from main domains (including Argent, Braavos, OG, Everai, and others). Below, there is a line graph showing the number of active domains viewable over 7 days, 1 month, 1 year, and all time like here for example https://dropstab.com/coins/ethereum

You can use the library of chart.js for line chart : https://www.chartjs.org/docs/latest/charts/line.html

Design link : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3707-8937&t=IRst8YakJD5xUctk-1

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by SudiptaPaul-31** [comment]
Would love to contribute to this issue. I am a fullstack developer

**Comment by akintola4** [comment]
I just went through the design and saw how the ui was made, 

3 major sections 

-navbar: noticed it a reusable  component 
-info on total domains and sub domains
-chart with chart.js

Responsive to mobile view 

I know i should be able to attend to this issue and Implement the solution, thank you for you consideration

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by chigozzdevv** [comment]
Hello, please can I take over this issue? Thanks

**Comment by olisaagbafor** [comment]
May I take care of this?

**Comment by 0xDeon** [comment]
I'd like to take this issue.

Good day, I'm Deon a frontend develop with sufficient experience in building visualy appealing & responsive UI designs.

How i Hope to tackle this
Integrate Chart.js for the line graph.
Fetch and display analytics data
Implement time-range filters for the graph

ETA: 48 hrs

**Comment by fricoben** [comment]
This should have been created in the stats repo, I cloned it here https://github.com/lfglabs-dev/stats.starknet.id/issues/32
